POST http://localhost:3000/user
Content-Type: application/json

  {

  "FirstName": "Asta",
  "LastName": "Clover",
  "userName": "Vermilion",
  "email": "Asta@gmail.com",
  "Password": "123456"   

  }

POST http://localhost:3000/admin
Content-Type: application/json

    {
      "UserName":"Fortune",
      "Email":"Fortune@gmail.com",
      "Password":"123456"
      
      }

GET http://localhost:3000/userdetail
Authorization: Bearer <sadasfsafwaf>


GET http://localhost:3000/UserProfile
Authorization: Bearer <sadasfsafwaf>

GET http://localhost:3000/project-sql
Authorization: Bearer <sadasfsafwaf>

PUT http://localhost:3000/UpdateUser
Authorization: Bearer <sadasfsafwaf>

PUT http://localhost:3000/BlockUser
Authorization: Bearer <sadasfsafwaf>

POST http://localhost:3000/login
Content-Type: application/json
//post.login
//Get.userdetail
//get.userprofile
//put.updateuser
//put.blockUser
